services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - ./src/main/resources/db/init-scripts:/docker-entrypoint-initdb.d

  auth-service:
    container_name: VoiceAuthService
    build: .
    ports:
      - ${AUTH_SERVICE_PORT:-8080}:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db